### ISSUE TITLE
Method to add games to list?

### ISSUE THREAD

**Issue by Casuallynoted** [nesbox/time#6]
I was trying to see, is there an easy way to add titles to the list of, for example, nes games? I know that if you want to add other rom options, you can just place roms in the folder, which is really awesome, but I can't seem to find a way to add other options to the list.

**Comment by nesbox** [comment]
Hi,

all the games in nesbox.time are predefined and you can't add your own roms to the list
to play your your won games pls use the emulator here http://nesbox.github.io/emulator/
